name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: 빌드 시작
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./tetris"

    steps:
      - name: 코드 checkout
        uses: actions/checkout@v2

      - name: 노드 16v 설치
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
        working-directory: "./tetris"

      - name: 의존성 파일 설치
        run: yarn
        working-directory: "./tetris"

      - name: 테스트 코드 실행
        run: yarn test
        working-directory: "./tetris"
